### ISSUE TITLE
Want some help?

### ISSUE THREAD

**Issue by zkat** [voltpkg/volt#12]
Hi!

I'm the former lead dev for the official NPM CLI, the author of npx and the npm@5 release that got NPM matching Yarn speeds back in the day. Pretty much until NPM inc started union busting and firing all my colleagues lol 

I'm also an avid Rust user, and for a while, I was trying to write a package manager for js in Rust, too, in the form of https://github.com/orogene/orogene until I burned out and decided I'd rather be doing something else with that time.

This is all to say, I would love to help out, if only as an accessible resource for y'all when you're trying to navigate the way NPM &co typically do things, how to stay compliant with weird third party registries, and whatever else you might want to chat about! The "community" link on your site wasn't working but if there's a discord or something you'd like me to join and this seems like a good idea please lmk!

Anyway great job and I look forward to seeing where this project goes!

**Comment by XtremeDevX** [comment]
@zkat thank you so much for reaching out! You can join our discord server [here](https://discord.gg/amycXUQn) and I would love to chat about what we're doing at volt and I also had a few questions 🙂 . Looking forward to connecting with you!

**Comment by XtremeDevX** [comment]
Also regarding the website 😁, I just needed to get something quick and dirty on the domain, will be working on it after I get some more work done on the product!!

**Comment by zkat** [comment]
yay!
