### ISSUE TITLE
Clap for command line

### ISSUE THREAD

**Issue by Lodin** [voltpkg/volt#15]
**Is your feature request related to a problem? Please describe.**
I found that the project uses an own solution for displaying cli command description.

**Describe the solution you'd like**
I guess it would be profitable for the project to use the standard de-facto solution for the Rust CLI: the [clap](https://github.com/clap-rs/clap) crate. It has a lot of nice features that would reduce an amount of code that is needed to support.

**Comment by Acidic9** [comment]
I would agree with you here. Clap would've definitely been the best choice.. but there's been a lot of work on volt already, I'm not sure if it's worth changing currently as our current approach is working fine.

But I think it's worth keeping our minds open for it.

**Comment by XtremeDevX** [comment]
@Lodin thanks for pointing this out 😃, although it would be much easier to use clap for parsing, we also get a large overhead with clap. That being said, clap is a great library and I'll look into it if we have any issues with the manual parsing that we're doing now down the line

**Comment by Lodin** [comment]
@XtremeDevX,

> we also get a large overhead with clap

Oh, does it produce so much overhead? I thought it is pretty fast and performant enough to just take it and use.

**Comment by XtremeDevX** [comment]
![unknown](https://user-images.githubusercontent.com/63039748/129035790-e2330cf6-3d1f-419e-937c-08236d3199b4.png)

**Comment by XtremeDevX** [comment]
Perhaps we could look into Pico args
