### ISSUE TITLE
Crediting External Libraries

### ISSUE THREAD

**Issue by firedupmike** [voltpkg/volt#8]
Hi there,

From what I can see, you all have just lifted code from multiple crates without any acknowledgement at all. This is legally infringing even if you're copying from permissively licensed crates. Please create a file stating what all third party code has been used.

**Comment by XtremeDevX** [comment]
Hello, yes we are aware of this and we are yet to credit these crates on the readme. We will add it now.

**Comment by firedupmike** [comment]
Just for an example:
https://github.com/voltpkg/volt/tree/master/junction is directly lifted from junction

And there are several files scattered across. You should maintain a list of what all third party code is used and then point to their locations and clearly mention that in the readme stating that "This repository contains third party code from ..."

Hopefully you get this set before the authors create reports

**Comment by XtremeDevX** [comment]
The readme has been
 updated

**Comment by XtremeDevX** [comment]
@firedupmike Would you like us to create a `CREDITS.md`?

**Comment by firedupmike** [comment]
If you have a small number of things to list, then the README seems fine. If you have too many, maybe state "This project uses third party code from different crates and a list of them can be found here," linking to the credits file. That's how it is doneBest,Mike (aka Will)Sent from my iPhoneOn 6/11/21, 6:21 PM Tejas Ravishankar ***@***.***> wrote:

   
  @firedupmike Would you like us to create a CREDITS.md?

**Comment by XtremeDevX** [comment]
Cool thanks for bringing this up will do in an hour when I'm free

**Comment by firedupmike** [comment]
Looks like GitHub never learned to format email contents :/

**Comment by XtremeDevX** [comment]
@firedupmike we are now maintaining an active list of packages in our `CREDITS.md` and we're linked that to the `README.md`. Thanks for raising this issue and I will be closing it now :)

**Comment by firedupmike** [comment]
> @firedupmike we are now maintaining an active list of packages in our `CREDITS.md` and we've linked that to the `README.md`. Thanks for raising this issue and I will be closing it now :)

Your way of maintaining the credits is incorrect. For the sources that have been copied, state which directory from the source tree contains it and its corresponding license.

For example, for the junction folder, add a README.md and link to the original source and license. Your README should state something like:

Volt is licensed under Apache-2 and uses source code from junction in (/path/to/junction/in/your/tree) that is released under the MIT License(link to repo), rustc_lint in (/path) that is released under the Apache license(link to repo), ....

Nowhere are you stating that your codebase itself contains third party code and not via dependencies.

**Comment by firedupmike** [comment]
I mean you're literally copying all the repos of an entire project in your source code. Why can't you dynamically link it i.e via a dependency? Also, if you really need some changes, why not PR upstream? This is disgustingly bad practice in open source

**Comment by XtremeDevX** [comment]
We're using `junction` and the rslint set of libraries because:
1. Current `junction` crate is completely broken (we're also removing it as a dependency because we no-longer need junctions)
2. RSLint is yet to release a new version to crates.io so we're waiting for that, I'm in touch with rslint developer

**Comment by firedupmike** [comment]
@XtremeDevX why can't you just use submodules to the repository upstream?

**Comment by XtremeDevX** [comment]
@firedupmike yep didn't think of that - will do soon

**Comment by XtremeDevX** [comment]
Also, we do need to have those rslint libraries physically there - we're customizing error messages etc.

**Comment by firedupmike** [comment]
@XtremeDevX And if you really need the changes, why can't you just use git linking in your dependencies? For example:
```toml
package = { git="linktorepo" }
```

Cargo also you to use git dependencies without having to use submodules at all? Read this:  https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

**Comment by firedupmike** [comment]
> Also, we do need to have those rslint libraries physically there - we're customizing error messages etc.

Huh? Isn't that what submodules are for?

**Comment by XtremeDevX** [comment]
> Also, we do need to have those rslint libraries physically there - we're customizing error messages etc.

because this - we're customizing errors on rslint

**Comment by firedupmike** [comment]
> > Also, we do need to have those rslint libraries physically there - we're customizing error messages etc.
> 
> because this - we're customizing errors on rslint

And I'm sure you can map_err in many cases since most of the errors use std's result enumeration. And these will anyways be optimized by the compiler when you build your binary

**Comment by XtremeDevX** [comment]
No - rslint is a linter, we're customizing its output messages

**Comment by XtremeDevX** [comment]
> > @firedupmike we are now maintaining an active list of packages in our `CREDITS.md` and we've linked that to the `README.md`. Thanks for raising this issue and I will be closing it now :)
> 
> Your way of maintaining the credits is incorrect. For the sources that have been copied, state which directory from the source tree contains it and its corresponding license.
> 
> For example, for the junction folder, add a README.md and link to the original source and license. Your README should state something like:
> 
> Volt is licensed under Apache-2 and uses source code from junction in (/path/to/junction/in/your/tree) that is released under the MIT License(link to repo), rustc_lint in (/path) that is released under the Apache license(link to repo), ....
> 
> Nowhere are you stating that your codebase itself contains third party code and not via dependencies.

I will do this.

**Comment by firedupmike** [comment]
Are you using this: https://docs.rs/rslint_core/0.2.2/rslint_core/?

**Comment by XtremeDevX** [comment]
No, that's an outdated version which does not have typescript support

**Comment by firedupmike** [comment]
Use upstream?

**Comment by firedupmike** [comment]
Via the git linking?

**Comment by XtremeDevX** [comment]
We need to customize the errors which have been output from rslint

**Comment by XtremeDevX** [comment]
that's why we're maintaining physical crates

**Comment by firedupmike** [comment]
> > > @firedupmike we are now maintaining an active list of packages in our `CREDITS.md` and we've linked that to the `README.md`. Thanks for raising this issue and I will be closing it now :)
> > 
> > 
> > Your way of maintaining the credits is incorrect. For the sources that have been copied, state which directory from the source tree contains it and its corresponding license.
> > For example, for the junction folder, add a README.md and link to the original source and license. Your README should state something like:
> > Volt is licensed under Apache-2 and uses source code from junction in (/path/to/junction/in/your/tree) that is released under the MIT License(link to repo), rustc_lint in (/path) that is released under the Apache license(link to repo), ....
> > Nowhere are you stating that your codebase itself contains third party code and not via dependencies.
> 
> I will do this.

This is important. Also, try to keep the LICENSE and README for the crates intact. There have been so many open source licensing legalities.

**Comment by XtremeDevX** [comment]
Sure, will do

**Comment by XtremeDevX** [comment]
I literally cloned the crates over here https://github.com/rslint/rslint. So it shouldn't be any issue. The crates don't have a README or a LICENSE attached.

**Comment by XtremeDevX** [comment]
> > > @firedupmike we are now maintaining an active list of packages in our `CREDITS.md` and we've linked that to the `README.md`. Thanks for raising this issue and I will be closing it now :)
> > 
> > 
> > Your way of maintaining the credits is incorrect. For the sources that have been copied, state which directory from the source tree contains it and its corresponding license.
> > For example, for the junction folder, add a README.md and link to the original source and license. Your README should state something like:
> > Volt is licensed under Apache-2 and uses source code from junction in (/path/to/junction/in/your/tree) that is released under the MIT License(link to repo), rustc_lint in (/path) that is released under the Apache license(link to repo), ....
> > Nowhere are you stating that your codebase itself contains third party code and not via dependencies.
> 
> I will do this.

Will still do this tho

**Comment by firedupmike** [comment]
That means all of them are licensed under the same license?

**Comment by XtremeDevX** [comment]
Correct - MIT License

**Comment by firedupmike** [comment]
> I literally cloned the crates over here https://github.com/rslint/rslint. So it shouldn't be any issue. The crates don't have a README or a LICENSE attached.

So you should have cloned the licenses in each file/dir. Why don't you create one single large directory with all the other crates and name it rustlint and add the readme and License there? That simplifies things greatly. Cargo allows you to specify paths at will: "../../wherever"

**Comment by XtremeDevX** [comment]
I'm currently working on a whole project restructure, will do it then

**Comment by XtremeDevX** [comment]
Also, if you don't mind me asking would love a ⭐ (only if you want to of course)

**Comment by firedupmike** [comment]
Also it'd be nice to state "We use rslint for linting" directly on your README and link back to rslint and their Open collective page. If you know, Riccardo has spent a huge amount of time and effort on this.

**Comment by XtremeDevX** [comment]
@firedupmike that's what the CREDITS.md is for though. We do not want a cluttered README.
